name: run-tests

on:
  pull_request:
    branches: [master]  # says "run when there's a PR req into the master branch"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run cypress tests
        uses: cypress-io/github-action@v5.1.0
        with:
          build: npm run build
          start: npm run dev
